### ISSUE TITLE
PICTURE_DELAY maximum value

### ISSUE THREAD

**Issue by BL08FR** [Winston-Lu/ESP32-Cam-Timelapse#3]
I expected to take a photo every 24H but somewhere between PICTURE_DELAY value of 950 and 3600 the Esp32cam take photos continuously (at 950s it's still ok, at 3500 it's not).

I don't understand why, uint64_t max value is so huge that I doubt it can be the reason. Is it normal or no and do you know why?

As you can see in log below, it crash after "Serial.println("Startup");"
I believe it could be relative to the next line "WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable brownout detector".

Serial monitoring below (it's cycle) :

13:24:51.738 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:51.738 -> configsip: 0, SPIWP:0xee
13:24:51.738 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:51.738 -> mode:DIO, clock div:1
13:24:51.738 -> load:0x3fff0030,len:1344
13:24:51.738 -> load:0x40078000,len:13864
13:24:51.738 -> load:0x40080400,len:3608
13:24:51.738 -> entry 0x400805f0
13:24:52.240 -> Startup
13:24:53.096 -> ets Jun  8 2016 00:22:57
13:24:53.096 -> 
13:24:53.096 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:53.096 -> configsip: 0, SPIWP:0xee
13:24:53.096 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:53.096 -> mode:DIO, clock div:1
13:24:53.096 -> load:0x3fff0030,len:1344
13:24:53.096 -> load:0x40078000,len:13864
13:24:53.096 -> load:0x40080400,len:3608
13:24:53.096 -> entry 0x400805f0
13:24:53.597 -> Startup
13:24:54.199 -> ets Jun  8 2016 00:22:57
13:24:54.199 -> 
13:24:54.199 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:54.199 -> configsip: 0, SPIWP:0xee
13:24:54.199 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:54.199 -> mode:DIO, clock div:1
13:24:54.199 -> load:0x3fff0030,len:1344
13:24:54.246 -> load:0x40078000,len:13864
13:24:54.246 -> load:0x40080400,len:3608
13:24:54.246 -> entry 0x400805f0
13:24:54.748 -> Startup
13:24:55.302 -> ets Jun  8 2016 00:22:57
13:24:55.302 -> 
13:24:55.302 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:55.302 -> configsip: 0, SPIWP:0xee
13:24:55.302 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:55.349 -> mode:DIO, clock div:1
13:24:55.349 -> load:0x3fff0030,len:1344
13:24:55.349 -> load:0x40078000,len:13864
13:24:55.349 -> load:0x40080400,len:3608
13:24:55.349 -> entry 0x400805f0
13:24:55.851 -> Startup
13:24:56.606 -> ets Jun  8 2016 00:22:57
13:24:56.606 -> 
13:24:56.606 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:56.606 -> configsip: 0, SPIWP:0xee
13:24:56.606 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:56.606 -> mode:DIO, clock div:1
13:24:56.606 -> load:0x3fff0030,len:1344
13:24:56.606 -> load:0x40078000,len:13864
13:24:56.606 -> load:0x40080400,len:3608
13:24:56.606 -> entry 0x400805f0
13:24:57.108 -> Startup
13:24:57.710 -> ets Jun  8 2016 00:22:57
13:24:57.710 -> 
13:24:57.710 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:24:57.710 -> configsip: 0, SPIWP:0xee
13:24:57.710 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:24:57.710 -> mode:DIO, clock div:1
13:24:57.710 -> load:0x3fff0030,len:1344
13:24:57.710 -> load:0x40078000,len:13864
13:24:57.710 -> load:0x40080400,len:3608
13:24:57.710 -> entry 0x400805f0
13:24:58.211 -> Startup
13:24:58.813 -> ets Jun  8 2016 00:22:57

Thanks for reading.

**Comment by Winston-Lu** [comment]
My only guess right now is that something in the library might be taking this in as a 32 bit integer. I can make a workaround for longer times but it should be able to handle 64 bit integers like you mentioned. I don't have much time to check, but can you see if replacing this on line 51 works?
```c
esp_sleep_enable_timer_wakeup(4294967296); //Init timer
```
This should be about 1.19 hours and more than what a 32 bit integer can handle. If its 64 bit then it should handle it fine. Otherwise I can code in a workaround.

From the error log I assume once you set a high enough number it just boot loops?

**Comment by BL08FR** [comment]
Hello,

I didn't tried what you said because our discussion about 64 bit made me find ask myself if the multiplication with the two uint64_t value was itself resulting in a uint64_t.
And I found this subject very similar to what I experienced : https://arduino.stackexchange.com/questions/91670/esp32-can-not-deep-sleep-longer-than-35-minutes

So I replaced line 51 by : esp_sleep_enable_timer_wakeup(1000000ULL * STARTUP_DELAY); //Init timer
And line 156 by : esp_sleep_enable_timer_wakeup(1000000ULL * PICTURE_DELAY);

And it seem to work now at least with 3600 (1h).
You may edit the code with it.
Note that "#define uS_TO_S_FACTOR 1000000" become useless with this.

**Comment by Winston-Lu** [comment]
Added commit faeb91f9d01b66052409a80b3078d20a40a45d76 to implement the explicit 64 bit integer cast
